[package]
name = "migration"
version.workspace = true
edition.workspace = true
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]

[dependencies.sea-orm-migration]
version = "0.12"
features = []
