[workspace]
members = [ "schema","server"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
flashmind-schema = { path = "./schema" }

serde = { version = "1" }