version: "3.8"

services:
  flashmind-db:
    image: mariadb:latest
    volumes:
      - flashmind-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MARIADB_DATABASE: flashmind

  flashmind:
    # build: .
    image: local/flashmind
    networks:
      - web
      - default
    env_file: .prod.env
    labels:
      traefik.enable: "true"
      traefik.http.routers.flashmind.entrypoints: web-secure
      traefik.http.routers.flashmind.rule: Host(`flashmind.m00nlit.dev`) && PathPrefix(`/api`)
      # traefik.http.routers.flashmind.middlewares: flashmind-cors

      traefik.http.middlewares.flashmind-cors.headers.accessControlAllowMethods: "*"
      traefik.http.middlewares.flashmind-cors.headers.accessControlAllowHeaders: "*"
      traefik.http.middlewares.flashmind-cors.headers.accessControlAllowOriginList: "http://localhost:1420,https://flashmind.m00nlit.dev"
      traefik.http.middlewares.flashmind-cors.headers.accessControlAllowCredentials: "true"

  flashmind-front:
    image: local/flashmind-front
    networks:
      - web
      - default
    labels:
      traefik.enable: "true"
      traefik.http.routers.flashmind-front.entrypoints: web-secure
      traefik.http.routers.flashmind-front.rule: Host(`flashmind.m00nlit.dev`)

volumes:
  flashmind-db-data:

networks:
  default:
  web:
    external: true
