version: "3.8"

services:
  flashmind-db:
    image: mariadb:latest
    volumes:
      - flashmind-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MARIADB_DATABASE: flashmind

  flashmind:
    # build: .
    image: local/flashmind
    networks:
      - web
      - default
    env_file: .env
    labels:
      traefik.enable: "true"
      traefik.http.routers.flashmind.entrypoints: web-secure
      traefik.http.routers.flashmind.rule: Host(`flashmind.m00nlit.dev`)

volumes:
  flashmind-db-data:

networks:
  default:
  web:
    external: true