[package]
name = "entity"
version.workspace = true
edition.workspace = true

[dependencies]
sea-orm.workspace = true

#rustc-hash = "1"
uuid = "1.7"

serde = { workspace = true, features = ["derive"] }
serde_json = "1"

ts-rs = "7.1"
