[package]
name = "entity"
version.workspace = true
edition.workspace = true

[dependencies]
sea-orm.workspace = true

serde = { workspace = true, features = ["derive"] }
serde_json = "1"

rustc-hash = "1"
