[package]
name = "server"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }

serde = { workspace = true, features = ["derive"]}

mongodb = "2.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

flashmind-schema.workspace = true
futures = "0.3"