// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Kind } from "./Kind";
import type { Share } from "./Share";

export interface Deck { name: string, kind: Kind, share: Share, }