// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {FlashCardItem} from "./FlashCardItem";
import type {Language} from "./Language";

export type FlashCardSection =
    "Separator"
    | FlashCardItem
    | { front: FlashCardItem, back: FlashCardItem, }
    | Record<Language, FlashCardItem>;