// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlashCardContent } from "./FlashCardContent";
import type { Share } from "./Share";

export interface FlashCard { share: Share, content: FlashCardContent, }