//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use super::sea_orm_active_enums::Kind;
use super::sea_orm_active_enums::Share;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "deck")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false, column_type = "custom(\"uuid\")")]
	pub uid: String,
	#[sea_orm(column_type = "Text")]
	pub name: String,
	pub creator: u32,
	pub kind: Kind,
	pub share: Share,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::followed_decks::Entity")]
	FollowedDecks,
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::Creator",
		to = "super::user::Column::Id",
		on_update = "Restrict",
		on_delete = "Restrict"
	)]
	User,
}

impl Related<super::followed_decks::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::FollowedDecks.def()
	}
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef {
		super::followed_decks::Relation::User.def()
	}
	fn via() -> Option<RelationDef> {
		Some(super::followed_decks::Relation::Deck.def().rev())
	}
}

impl ActiveModelBehavior for ActiveModel {}
