//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use super::sea_orm_active_enums::Share;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::data::flash_card::FlashCardContent;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "flash_card")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false, column_type = "custom(\"uuid\")")]
	#[serde(skip_deserializing)]
	pub uid: String,
	pub creator: u32,
	pub share: Share,
	#[sea_orm(column_type = "custom(\"LONGTEXT\")")]
	pub content: FlashCardContent,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::deck_cards::Entity")]
	DeckCards,
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::Creator",
		to = "super::user::Column::Id",
		on_update = "Restrict",
		on_delete = "Restrict"
	)]
	User,
}

impl Related<super::deck_cards::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::DeckCards.def()
	}
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::User.def()
	}
}

impl Related<super::deck::Entity> for Entity {
	fn to() -> RelationDef {
		super::deck_cards::Relation::Deck.def()
	}
	fn via() -> Option<RelationDef> {
		Some(super::deck_cards::Relation::FlashCard.def().rev())
	}
}

impl ActiveModelBehavior for ActiveModel {}
