//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::deck::Entity as Deck;
pub use super::flashcard::Entity as FlashCard;
pub use super::followed_decks::Entity as FollowedDecks;
pub use super::subject_id::Entity as SubjectId;
pub use super::user::Entity as User;
