//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub mod prelude;

pub mod deck;
pub mod deck_cards;
pub mod flash_card;
pub mod followed_decks;
pub mod sea_orm_active_enums;
pub mod user;
pub mod custom;
