//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

#[rustfmt::skip]
pub use super::deck::Entity as Deck;
#[rustfmt::skip]
pub use super::deck_cards::Entity as DeckCards;
#[rustfmt::skip]
pub use super::flash_card::Entity as FlashCard;
#[rustfmt::skip]
pub use super::followed_decks::Entity as FollowedDecks;
#[rustfmt::skip]
pub use super::user::Entity as User;
